# Generated by Django 5.0.6 on 2024-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(choices=[('Food', 'Food'), ('Culture', 'Culture'), ('Personal', 'Personal')], default='Food', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
