# Generated by Django 5.0.6 on 2024-05-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('publish_blogpost', 'Can publish a BlogPost')]},
        ),
    ]
