# Generated by Django 5.0.6 on 2024-05-15 07:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 12, 31)),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Unknown Organizer', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=255),
        ),
    ]
