# Generated by Django 5.0.6 on 2024-05-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_event_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_published',
        ),
    ]
