# Generated by Django 5.0.6 on 2024-05-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_event_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='topic',
        ),
    ]
