# Generated by Django 5.0.6 on 2024-05-22 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='num_views',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='conclusion',
            field=models.TextField(default="Conclusion de l'article..."),
        ),
        migrations.AddField(
            model_name='article',
            name='infographic',
            field=models.ImageField(default='images/default.png', upload_to='infographics/'),
        ),
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(default="Introduction à l'article..."),
        ),
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.URLField(default='http://www.example.com'),
        ),
        migrations.AddField(
            model_name='article',
            name='practical_tips',
            field=models.TextField(default='Conseils pratiques et recommandations pour les agriculteurs...'),
        ),
        migrations.AddField(
            model_name='article',
            name='technical_info',
            field=models.TextField(default='Informations techniques sur les techniques agricoles...'),
        ),
        migrations.AddField(
            model_name='article',
            name='testimonials',
            field=models.TextField(default="Témoignages d'agriculteurs ou d'experts du secteur..."),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default="Titre de l'article", max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
    ]
